#!/bin/bash

# Define minimum required arguments
MIN_ARGS=2

# Check if enough arguments were provided
if [ $# -lt $MIN_ARGS ]; then
  echo "Error: Please provide both RESOURCE_TYPE and NAMESPACE arguments!"
  exit 1
fi

# Define command-line arguments

RESOURCE_TYPE=$1
NAMESPACE=$2

# Retrieve resource usage statistics from Kubernetes
kubectl get $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract resource name, CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
